version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/database:/usr/src/app/database
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
